Home work1 Anastasiia_Aliinyk
anastasiiaAliinyk/Front-end_2021 pull request #1
Opened 2021-05-27 12:51 UTC by anastasiiaAliinyk

[DEMO LINK](https://anastasiiaaliinyk.github.io/Front-end_2021/)

2021-05-27 22:10 UTC, Korew requested changes
Please, read technical task.
1. I do not see proper sticky header (it should be sticky all the time, not only first 200px of scroll).
2. I do not see sticky tabs
3. No slider in Glossary section
4. No transitions for hover effects

When you fix mistakes - make sure you fix them everywhere in your project, not only where I left comments. Most of mistakes repeat all over the project. I assume if I left comment 1 or two times - you will fix same problem everywhere.

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +          <span class="item__number">
You can use css counter here - create `::before` element for `.item__wrap-number` and use [counter](https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters) in `content` property

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +          </div>
Why do you duplicate accordion header? Hide/show only answer, header should be only one and visible all the time

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +            <span class="item__number">
Move `Q` and `A` to `content` property in css for pseudo element `::before`

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +              <a href="#" class="header-menu-nav-link">
Very small area for click
![image](https://user-images.githubusercontent.com/17281920/119888493-1704cc00-bf3e-11eb-90cb-5774a4f5d78f.png)

On mobile it will be better to make `<a>` block element and add paddings on top and bottom. Do not forget to remove margin for `li`.

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +            </li>
It is better to move `Get Skout` and `Log In` to separate block. You can use flex to attach block with this two links to the bottom.

You've added margin for `nth-child(6)` - it is bad solution. Menu will be broken if you change number of links.

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +            <img src="images/1.png" alt="first-picture">
`alt` should contain meaningful text

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +                <img src="images/info.png" alt="information">
This picture does not have any semantic meaning for the content of the site, so you can add it as background for `<div class="hidden-content__info">`

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +            <img src="images/1.png" alt="first-picture">
In figma I see different images. Also all images can be exported as SVG - it is preferable to use this format

2021-05-27 22:10 UTC, Korew commented on src/main.js
> +      if (hiddenContent.style.display === "block") {
You started using single quotes - use them everywhere.

2021-05-27 22:10 UTC, Korew commented on src/main.js
> +buttonsSelectPlus.forEach(buttonSelectPlus => {
Use different name for `buttonSelectPlus` inside forEach. For example `btn` will be ok. Now it looks almost like `buttonsSelectPlus` - very difficult to read this code.

2021-05-27 22:10 UTC, Korew commented on src/main.js
> +    let itemNumber = hiddenContent.previousElementSibling;
`hiddenContent` and `itemNumber` never reassigned, use const

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +//RESET
split code to different files - reset.scss, layout.scss, header.scss etc.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  font-family: "Aclonica", sans-serif;
Be consistent in your code - use single or double quotes everywhere. Do not mix them.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  font-size: 12px;
Main content is 16px. This is the standard in web design. In most cases you need to change font-size only where it is necessary.

Please chack font-sizes - I see you have 14px where it should be 16px;

2021-05-27 22:10 UTC, Korew commented on src/scss/_variables.scss
> +$breakpoint-phone: 450px;
You do not need this breakpoint. We can assume that everything up to 768 pixels is phone.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  transition: 0.8s;
You can not animate `display` property. You can hide menu using `transform: translateX(-100%);` for example. And show by setting `translateX(0)`

Also when using transition - always good idea specify exact properties, that should be animated: `transition: transform .3s;`

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  height: 18px;
24x18px - pretty small size for tapping with finger. There is enough space to make clickable area much bigger.
![image](https://user-images.githubusercontent.com/17281920/119896150-479d3380-bf47-11eb-870a-fc88eeac873f.png)

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  -webkit-box-pack: justify;
You do not need to write prefixes manually in scss - they can be added automatically with gulp.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +        );
why three lines?

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    width: 0.5px;
1px width and 20px height will be ok.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    content: " ";
Single quotes. Space inside quotes not necessary, just `content: '';`

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    &:nth-child(6) {
I mentioned in html - it is not good idea to use nth-child(6) - imagine client will ask you to remove item from menu - your design will be broken. Always make sure everything will still look fine if content changes.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +      padding: 8px 54px;
Button size doesn't match design.

Lets calculate:
In design we see text height 24px and font-size 12px. So you have to set `line-height: 2;`
Border 1.5px - bad idea, use 1px. Also we see padding 8px on top and bottom, but it includes 1px border. So you need to set `padding: 7px 54px;` (54px should become 53px if you follow same logic, but width less important than height)

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    position: relative;
menu items doesn't match design. Don't forget about line-height.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  width: 80%;
Why 80%? You have to give margin to inside elements so they do not stick together.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  display: flex;
align-items: center will be good idea

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  & .item__wrap-number {
in this case you do not need `&`

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  & .item__wrap-number:first-of-type {
same - unnecessary `&`

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +      object-fit: contain;
This won't work. You need to set width and height of image to 100% and parent block should have specific size.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +        margin: 0 10% 0 0;
why 10% on the right?

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +      max-width: 464px;
I understand that you took 464px from design - but this is how Figma works. If there was different text, size would be different too.

Try to limit width of this block by settings margin for image on the left and paddings for parent block.

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  & > .l-container {
`&` is unnecessary in this case

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  background: no-repeat url("../images/scout-bc.jpg");
use gradient instead of image

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +      display: flex;
horizontal scroll on 992px screen width
![image](https://user-images.githubusercontent.com/17281920/119900843-baa9a880-bf4d-11eb-9181-11a54f019947.png)

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +              <span class="glossary-slider__arrow-left"></span>
Suppose to be buttont

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    background: no-repeat url("../images/left.png");
export image as svg

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    opacity: 0.5;
Opacity .5 not for left button, but for disabled button. Right button can be disabled too, so it will have opacity .5

Use same class for left and right button. You can even use same image and rotate one of the buttons 180 degrees. Then add opacity:
```
button[disabled] {
  opacity: .5;
}
```

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +    transition: 0.5s;
specify properties that should be animated

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +      margin: 0 0 0 30px;
when you want to set margin only on one side, it is better to write `margin-left: 30px;`

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +      width: 270px;
why 270px? Control size by adding margins to neighbor elements and padding to parent element

2021-05-27 22:10 UTC, Korew commented on src/scss/style.scss
> +  outline: none;
Never remove default focus state unless you add your own.

2021-05-27 22:10 UTC, Korew commented on src/index.html
> +              If you are interested in trying our platform but aren’t ready to buy, please reach out to us and we can try to work something out. SKOUT issues trial programs on a case by case basis.
According to design - you should have a link in this block. It is not a problem, you do not have link in html code - content can be changed anytime not by you. Problem, that you do not have styles for that link - I've added one and it looks like text.

![image](https://user-images.githubusercontent.com/17281920/119903531-80420a80-bf51-11eb-8e40-68512a8864c1.png)

2021-06-03 12:42 UTC, anastasiiaAliinyk commented
Было очень много замечаний, надеюсь нигде не упустила)

2021-06-03 19:53 UTC, Korew commented
Please, next time assign PR to reviewer 
![image](https://user-images.githubusercontent.com/17281920/120703885-8f2f3c80-c4be-11eb-93c2-81a674545ba1.png)

2021-06-03 22:09 UTC, Korew approved these changes
Pay attention to similar parts in design - for example three sections have a lot in common - you could write some styles and apply them to all sections.

Much more better, but still a lot of things can be improved - please read my comments and keep them in mind.

Good job!

2021-06-03 22:09 UTC, Korew commented on gulpfile.js
> +let sass = require('gulp-sass');
variables never reassigned - use `const`

2021-06-03 22:09 UTC, Korew commented on src/css/basic.css
> +html {
1. You don't need to compile all scss files separately - please, name files starting with underscore symbol `_` so they won't be processed by gulp (like `_reset.scss`). You should have only 1 compiled file in css folder

2. Add css folder to gitignore

2021-06-03 22:09 UTC, Korew commented on src/images/empowering.svg
> +<svg width="371" height="370" viewBox="0 0 371 370" fill="none" xmlns="http://www.w3.org/2000/svg">
minify all svg files - https://jakearchibald.github.io/svgomg/

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +          <img src="images/tips.png" alt="TIPS" class="tips-title">
All images can be exported as svg.

Images looks different in design - but probably it designer's mistake. Obviously, these pictures should have the same proportions on both mobile and desktop.

If you use svg - you won't need separate images for mobile and desktop - you can just change size for desktop image in css.

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +              System Patching
Follow indentations

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +          <label class="tips-accordion-label" for="check-t1">
Interesting solution with checkbox - nice.

But I don't see focus state

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +                </p><br>
`<br>` you don't need it here - use margins for `p` element

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +            id="check-t3"
if you put `input` inside `label`, you don't need `id` and `for` attributes

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +                  <span></span>
you do not need separat `span` for icon - add it as background to parent element `.tips-accordion-info` (do not forget to add left padding too)

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +            <img src="images/glossary.png" alt="GLOSSARY" class="glossary-title">
could be svg, do not use CAPS for alt text, `Glossary` would be ok. `Skout Glossary` even better

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +      <div class="container wraper">
Why you have two classes here?
`.glossary .container` would be the same:
![image](https://user-images.githubusercontent.com/17281920/120707004-74f75d80-c4c2-11eb-92c0-03e96e740101.png)

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +              <p>
It is not always necessary to split code into multiple lines.
`<p>SKOUT will work on Windows, Mac, and Linux environments.</p>`

But your version is also valid - everything is ok.

2021-06-03 22:09 UTC, Korew commented on src/index.html
> +          MORE QUESTIONS
Do uppercase in css

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +const topMenu = document.querySelector('#menu');
When selecting by ID use `getElementById`

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +//Change top menu styles when scrolling
space after `//`

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +  if (top >= headerHeight && width > 1120) {
`>=` useless here, just `>` would work almost same (nobody can notice difference)

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +
empty line not needed here

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +  const width = window.screen.width;
this width and css media-query width slightly different. Use [matchMedia](https://developer.mozilla.org/ru/docs/Web/API/Window/matchMedia)

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +    topMenuContainer.style.background = 'linear-gradient(to left, #00f473 15%, #22c6d4 80%, #17c3e1)';
Use class for this. Linear-gradient requires prefixes for different browsers.

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +  if(top >= (headerHeight - topMenu.clientHeight + 10)) {
space after `if`

2021-06-03 22:09 UTC, Korew commented on src/js/main.js
> +        breakpoint: 1120,
Slick has `mobileFirst` option. Just for information, no need to change this.

2021-06-03 22:09 UTC, Korew commented on src/scss/_normolize.scss
> +html {
What is `normolize`? ))

Are you sure you need separate file for this code? You could create `_common.scss` or `_general.scss` and move code from `main`, `normOlize`, `container` etc. there.

2021-06-03 22:09 UTC, Korew commented on src/scss/_normolize.scss
> +.slick-track{
space before `{`

2021-06-03 22:09 UTC, Korew commented on src/scss/_variables.scss
> +$breakpoint-phone: 450px;
Where did you use this var?

2021-06-03 22:09 UTC, Korew commented on src/scss/container.scss
> +@import 'variables';
you don't need to import variables in each file (if you follow recommendations I gave you above)

2021-06-03 22:09 UTC, Korew commented on src/scss/faqs.scss
> +    border-top: 1px solid #b2b2b2;
```
@media(min-width: $breakpoint-tablet) {
  padding-top: 19px;
}
```

you can add media-queries right here

2021-06-03 22:09 UTC, Korew commented on src/scss/faqs-accordion.scss
> +  }
use scss:
```
input {
  ...

  &:checked {
    + .faqs-accordion-label::after {
      ...
    }

    ~ .faqs-accordion-content-wraper {
      ..
    }
  }
}

2021-06-03 22:09 UTC, Korew commented on src/scss/faqs-accordion.scss
> +    display: inline-block;
Why you need inline-block for simple link?

This is just a link inside content - any content on your site can have links - better to add styles for `a` element generally. So anytime you use `<a>` it will be green.

Links in header/footer are different - you still need unique styles for them.

2021-06-03 22:09 UTC, Korew commented on src/scss/tips.scss
> +  counter-reset: section;
This counter is used in another file - no need to create so many files - you could use one for tips section.

2021-06-03 22:09 UTC, Korew commented on src/scss/tips.scss
> +    border-top: 1px solid #b2b2b2;
Move color to variables. This is top border of section (or section title) - it is used on all three sections, but you use it only twice. For Glossary section you made another border.

2021-06-03 22:09 UTC, Korew commented on src/scss/header.scss
> +.header {
This is first element in your html. Better if in css it will be first too

2021-06-03 22:09 UTC, Korew commented on src/scss/menu.scss
> +      border: 1px solid $c-white;
only border-color has changed. You could see this, if you wrote media-query inside `__loging-btn` block above

2021-06-03 22:09 UTC, Korew commented on src/scss/menu.scss
> +      transition: border $animation-time ease-in;
you already have same property above

2021-06-03 22:09 UTC, Korew commented on src/scss/slider-big.scss
> +      line-height: 36px;
no need to change line-height - use relative value and it will depend on font-size.

2021-06-03 22:09 UTC, Korew commented on src/scss/slider.scss
> +    background: url('../images/previous.svg') 0 0 / 100% no-repeat;
you could export only arrow, add circle as a border in css and use same arrow for next and prev button.

2021-06-03 22:09 UTC, Korew commented on src/scss/slider.scss
> +    left: -135px;
why -135px?
`left: calc(#{$max-width-container} / 2 - 50vw);`
this will move the block to the left side of the screen. But I'm not sure it is the best solution. Probably you need to talk to designer :)

2021-06-03 22:09 UTC, Korew commented on src/scss/tabs-menu.scss
> +    height: 40px;
better if you add paddings to link, so I can click on larger area
![image](https://user-images.githubusercontent.com/17281920/120716579-e89f6780-c4ce-11eb-8ed3-d489e5227d13.png)

2021-06-03 22:09 UTC, Korew commented on src/scss/tabs-menu.scss
> +    &--active {
When clicking tabs - you need to move this class to another link in js

2021-06-03 22:09 UTC, Korew commented on src/scss/tabs-menu.scss
> +      height: 80px;
do not hardcode height. Change paddings.

2021-06-03 22:09 UTC, Korew commented on src/scss/tips-accordion.scss
> +    opacity: 0;
It is not the best way to hide input - you can watch [this video](https://www.youtube.com/watch?v=E6kLaaQFctU)

2021-06-03 22:59 UTC, merged