Home work2
anastasiiaAliinyk/Front-end_2021 pull request #2
Opened 2021-06-13 17:33 UTC by anastasiiaAliinyk

[DEMO LINK](https://anastasiiaaliinyk.github.io/Front-end_2021/)

2021-06-14 08:53 UTC, Maxim-Bondar commented on 2/css/main.css
> +@import url("https://fonts.googleapis.com/css2?family=Actor&display=swap");
css forder must be in .gitignore

2021-06-14 08:57 UTC, Maxim-Bondar commented on 2/index.html
> +          <a class="essential-info"></a>
it is not a link, here probably must be a span, because you just create an icon here

2021-06-14 09:00 UTC, Maxim-Bondar commented on 2/index.html
> +        <div class="img-wrapper">
is it possible to change tag `div` to `button` here? because it is clickable area

2021-06-14 09:04 UTC, Maxim-Bondar commented on 2/src/images/empowering.svg
> +<svg width="93" height="105" viewBox="0 0 93 105" fill="none" xmlns="http://www.w3.org/2000/svg">
all svg must be minified, use this tool https://jakearchibald.github.io/svgomg/

2021-06-14 09:10 UTC, Maxim-Bondar commented on 2/src/scss/_about.scss
> +      max-width: 600px;
if you declare strict style property width, and you need override max-width, just set 100%

2021-06-14 09:13 UTC, Maxim-Bondar commented on 2/src/scss/_about.scss
> +    button:first-of-type {
what if yu will have 3 buttons here? use button + button {margin-top} , it will give you more flexebility in your layout

2021-06-14 09:15 UTC, Maxim-Bondar commented on 2/src/scss/_card.scss
> +  font-size: 12px;
font-size also can be taken from variables

2021-06-14 09:15 UTC, Maxim-Bondar commented on 2/src/scss/_card.scss
> +  background-color: white;
use HEX instead

2021-06-14 09:16 UTC, Maxim-Bondar commented on 2/src/scss/_card.scss
> +  button {
use class instead of tag selector

2021-06-14 09:18 UTC, Maxim-Bondar commented on 2/src/scss/_essentials.scss
> +      h4 {
use class instead of tag selector

2021-06-14 09:22 UTC, Maxim-Bondar requested changes
COMMON
- burger menu is not the same as on the design https://prnt.sc/15dbk51

2021-06-14 09:30 UTC, anastasiiaAliinyk commented
> COMMON
> 
> * burger menu is not the same as on the design https://prnt.sc/15dbk51

I did burger menu like it was in mobile version https://imgur.com/mOTG1LX
Should I change menu like it was in our home task 1?

2021-06-14 09:33 UTC, Maxim-Bondar commented
> > COMMON
> > 
> > * burger menu is not the same as on the design https://prnt.sc/15dbk51
> 
> I did burger menu like it was in mobile version https://imgur.com/mOTG1LX
> Should I change menu like it was in our home task 1?

Oh, my bad. Leave it as it is

2021-06-17 11:51 UTC, Maxim-Bondar approved these changes

2021-06-17 11:51 UTC, merged